import {
  ExpenseCategory,
  Wedding,
  Expense,
  WeddingEvent,
  WeddingTask,
  Guest,
  GuestAccommodation,
  GuestTransport,
  Vendor,
  VendorPayment,
  VendorDocument,
  WeddingMember,
  WeddingInvitation,
  WeddingActivity,
  WeddingMemory,
  MemoryMedia,
  MemoryPeopleTag,
} from '../types/database.types';
import { WEDDING_CATEGORIES } from '../constants/categories';

export const DEFAULT_CATEGORY_NAMES: Array<{ name: string; icon: string }> = WEDDING_CATEGORIES.map((c) => ({
  name: c.name,
  icon: c.icon,
  budget_limit: 0,
}));

export function createSampleWedding(ownerId: string): {
  wedding: Wedding;
  categories: ExpenseCategory[];
  expenses: Expense[];
  events: WeddingEvent[];
  tasks: WeddingTask[];
  guests: Guest[];
  accommodations: GuestAccommodation[];
  transports: GuestTransport[];
  vendors: Vendor[];
  vendorPayments: VendorPayment[];
  vendorDocuments: VendorDocument[];
  members: WeddingMember[];
  invitations: WeddingInvitation[];
  activities: WeddingActivity[];
  memories: WeddingMemory[];
  memoryMedia: MemoryMedia[];
  memoryPeopleTags: MemoryPeopleTag[];
} {
  const weddingId = 'sample-wedding-priya-arjun';
  
  // Set date to 45 days in future for realistic demo countdown
  const targetDate = new Date();
  targetDate.setDate(targetDate.getDate() + 45);
  const weddingDateStr = targetDate.toISOString().split('T')[0];

  const wedding: Wedding = {
    id: weddingId,
    owner_id: ownerId,
    wedding_name: "Priya & Arjun's Wedding",
    bride_name: 'Priya',
    groom_name: 'Arjun',
    wedding_date: weddingDateStr,
    total_budget: 800000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const categories: ExpenseCategory[] = DEFAULT_CATEGORY_NAMES.map((cat, idx) => {
    let budgetLimit = 0;
    if (cat.name === 'Venue') budgetLimit = 200000;
    else if (cat.name === 'Catering') budgetLimit = 200000;
    else if (cat.name === 'Clothing') budgetLimit = 100000;
    else if (cat.name === 'Decoration') budgetLimit = 80000;
    else if (cat.name === 'Photography') budgetLimit = 60000;
    else if (cat.name === 'Videography') budgetLimit = 40000;
    else if (cat.name === 'Jewellery') budgetLimit = 50000;
    else if (cat.name === 'Makeup') budgetLimit = 30000;
    else budgetLimit = 20000;

    return {
      id: `sample-cat-${idx + 1}`,
      wedding_id: weddingId,
      name: cat.name,
      icon: cat.icon,
      budget_limit: budgetLimit,
      created_at: new Date().toISOString(),
    };
  });

  const getCatId = (name: string) => categories.find((c) => c.name === name)?.id || null;

  const eventEngagementId = `sample-evt-1`;
  const eventMehendiId = `sample-evt-2`;
  const eventHaldiId = `sample-evt-3`;
  const eventSangeetId = `sample-evt-4`;
  const eventWeddingId = `sample-evt-5`;
  const eventReceptionId = `sample-evt-6`;

  const targetDateMs = targetDate.getTime();
  const dayMs = 86400000;
  const now = new Date();

  const expenses: Expense[] = [
    {
      id: 'sample-exp-1',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-1',
      vendor_payment_id: 'sample-vpm-1',
      category_id: getCatId('Venue'),
      event_id: eventWeddingId,
      expense_name: 'Venue Advance',
      amount: 150000,
      paid_by: 'Dad',
      payment_method: 'Bank Transfer',
      payment_status: 'Paid',
      expense_date: new Date(now.getTime() - 14 * 86400000).toISOString().split('T')[0],
      notes: 'Initial booking deposit for Palace Lawns',
      created_at: new Date(now.getTime() - 14 * 86400000).toISOString(),
      updated_at: new Date(now.getTime() - 14 * 86400000).toISOString(),
    },
    {
      id: 'sample-exp-2',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-2',
      vendor_payment_id: 'sample-vpm-2',
      category_id: getCatId('Catering'),
      event_id: eventReceptionId,
      expense_name: 'Catering Advance',
      amount: 95000,
      paid_by: 'Mom',
      payment_method: 'Bank Transfer',
      payment_status: 'Paid',
      expense_date: new Date(now.getTime() - 10 * 86400000).toISOString().split('T')[0],
      notes: 'Menu tasting and 25% booking confirmation',
      created_at: new Date(now.getTime() - 10 * 86400000).toISOString(),
      updated_at: new Date(now.getTime() - 10 * 86400000).toISOString(),
    },
    {
      id: 'sample-exp-3',
      wedding_id: weddingId,
      category_id: getCatId('Clothing'),
      event_id: eventWeddingId,
      expense_name: 'Bridal Lehenga',
      amount: 38500,
      paid_by: 'Sister',
      payment_method: 'Card',
      payment_status: 'Paid',
      expense_date: new Date(now.getTime() - 7 * 86400000).toISOString().split('T')[0],
      notes: 'Custom boutique lehenga with hand embroidery',
      created_at: new Date(now.getTime() - 7 * 86400000).toISOString(),
      updated_at: new Date(now.getTime() - 7 * 86400000).toISOString(),
    },
    {
      id: 'sample-exp-4',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-3',
      vendor_payment_id: 'sample-vpm-3',
      category_id: getCatId('Decoration'),
      event_id: eventSangeetId,
      expense_name: 'Decoration Advance',
      amount: 45000,
      paid_by: 'Dad',
      payment_method: 'UPI',
      payment_status: 'Paid',
      expense_date: new Date(now.getTime() - 4 * 86400000).toISOString().split('T')[0],
      notes: 'Mandap floral setup advance and fairy lights',
      created_at: new Date(now.getTime() - 4 * 86400000).toISOString(),
      updated_at: new Date(now.getTime() - 4 * 86400000).toISOString(),
    },
    {
      id: 'sample-exp-5',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-4',
      vendor_payment_id: 'sample-vpm-4',
      category_id: getCatId('Photography'),
      event_id: eventWeddingId,
      expense_name: 'Photographer Advance',
      amount: 25000,
      paid_by: 'Groom',
      payment_method: 'UPI',
      payment_status: 'Paid',
      expense_date: new Date(now.getTime() - 2 * 86400000).toISOString().split('T')[0],
      notes: 'Candid photographer booking for all 3 days',
      created_at: new Date(now.getTime() - 2 * 86400000).toISOString(),
      updated_at: new Date(now.getTime() - 2 * 86400000).toISOString(),
    },
    {
      id: 'sample-exp-6',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-5',
      vendor_payment_id: 'sample-vpm-5',
      category_id: getCatId('Makeup'),
      event_id: eventMehendiId,
      expense_name: 'Makeup Advance',
      amount: 15000,
      paid_by: 'Bride',
      payment_method: 'UPI',
      payment_status: 'Paid',
      expense_date: new Date(now.getTime() - 1 * 86400000).toISOString().split('T')[0],
      notes: 'Bridal HD makeup booking token',
      created_at: new Date(now.getTime() - 1 * 86400000).toISOString(),
      updated_at: new Date(now.getTime() - 1 * 86400000).toISOString(),
    },
  ];

  const events: WeddingEvent[] = [
    {
      id: eventEngagementId,
      wedding_id: weddingId,
      event_name: 'Ring Ceremony & Roka',
      event_type: 'Engagement',
      date: new Date(targetDateMs - 30 * dayMs).toISOString().split('T')[0],
      start_time: '06:00 PM',
      end_time: '10:00 PM',
      venue: 'The Grand Ballroom',
      description: 'Exchange of rings followed by formal family dinner',
      expected_guests: 150,
      budget_allocation: 150000,
      status: 'Completed',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: eventMehendiId,
      wedding_id: weddingId,
      event_name: 'Mehendi & High Tea',
      event_type: 'Mehendi',
      date: new Date(targetDateMs - 2 * dayMs).toISOString().split('T')[0],
      start_time: '03:00 PM',
      end_time: '07:00 PM',
      venue: 'Rose Garden Pavilion',
      description: 'Traditional henna ceremony with live folk singers & street chaat',
      expected_guests: 120,
      budget_allocation: 80000,
      status: 'Upcoming',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: eventHaldiId,
      wedding_id: weddingId,
      event_name: 'Haldi & Phoolon Ki Holi',
      event_type: 'Haldi',
      date: new Date(targetDateMs - 1 * dayMs).toISOString().split('T')[0],
      start_time: '10:30 AM',
      end_time: '01:30 PM',
      venue: 'Courtyard Mandap',
      description: 'Auspicious turmeric application, floral shower & dhol beats',
      expected_guests: 100,
      budget_allocation: 60000,
      status: 'Upcoming',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: eventSangeetId,
      wedding_id: weddingId,
      event_name: 'Sangeet Gala & DJ Night',
      event_type: 'Sangeet',
      date: new Date(targetDateMs - 1 * dayMs).toISOString().split('T')[0],
      start_time: '07:30 PM',
      end_time: '01:00 AM',
      venue: 'Imperial Lawn Stage',
      description: 'Choreographed family dances, live percussionist & cocktail dinner',
      expected_guests: 220,
      budget_allocation: 180000,
      status: 'Upcoming',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: eventWeddingId,
      wedding_id: weddingId,
      event_name: 'Auspicious Wedding & Varmala',
      event_type: 'Wedding',
      date: weddingDateStr,
      start_time: '06:00 PM',
      end_time: '11:30 PM',
      venue: 'Royal Palace Mandap',
      description: 'Baraat procession, varmala under floral canopy, sacred pheras & feast',
      expected_guests: 350,
      budget_allocation: 300000,
      status: 'Upcoming',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: eventReceptionId,
      wedding_id: weddingId,
      event_name: 'Grand Reception Dinner',
      event_type: 'Reception',
      date: new Date(targetDateMs + 1 * dayMs).toISOString().split('T')[0],
      start_time: '08:00 PM',
      end_time: '11:30 PM',
      venue: 'Royal Banquet Hall',
      description: 'Formal family welcome & feast with friends and extended community',
      expected_guests: 300,
      budget_allocation: 150000,
      status: 'Upcoming',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const tasks: WeddingTask[] = [
    {
      id: 'sample-task-1',
      wedding_id: weddingId,
      event_id: eventSangeetId,
      title: 'Confirm Sangeet DJ and Sound Setup',
      description: 'Finalize track list for bridal entry and family dance rounds',
      due_date: new Date(now.getTime() + 1 * dayMs).toISOString().split('T')[0],
      assigned_to: 'Dad',
      priority: 'Urgent',
      status: 'Todo',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-task-2',
      wedding_id: weddingId,
      event_id: eventWeddingId,
      title: 'Finalize Guest Rooms & Welcome Hampers',
      description: '18 rooms blocked at hotel, verify keycards and dry fruit boxes',
      due_date: new Date(now.getTime() + 3 * dayMs).toISOString().split('T')[0],
      assigned_to: 'Groom',
      priority: 'Important',
      status: 'Todo',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-task-3',
      wedding_id: weddingId,
      event_id: eventHaldiId,
      title: 'Review Haldi Marigold Floral Canopy Quote',
      description: 'Check requirement for 50kg fresh yellow and orange marigold blossoms',
      due_date: new Date(now.getTime() + 5 * dayMs).toISOString().split('T')[0],
      assigned_to: 'Mom',
      priority: 'Normal',
      status: 'Todo',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-task-4',
      wedding_id: weddingId,
      event_id: eventMehendiId,
      title: 'Collect Bridal Mehendi Lehenga from Boutique',
      description: 'Final fitting scheduled for afternoon with matching jewellery',
      due_date: new Date(now.getTime() + 8 * dayMs).toISOString().split('T')[0],
      assigned_to: 'Sister',
      priority: 'Important',
      status: 'Todo',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-task-5',
      wedding_id: weddingId,
      event_id: eventWeddingId,
      title: 'Book Vintage Car & Dhol Band for Baraat',
      description: 'Confirmed deposit of ₹15,000 for 8-piece brass dhol ensemble',
      due_date: new Date(now.getTime() + 12 * dayMs).toISOString().split('T')[0],
      assigned_to: 'Brother',
      priority: 'Urgent',
      status: 'In Progress',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  ];

  const guests: Guest[] = [
    {
      id: 'sample-gst-1',
      wedding_id: weddingId,
      full_name: 'Rajesh & Sunita Sharma',
      phone: '+91 98200 12345',
      email: 'rajesh.sharma@ukmail.co.uk',
      family_group: 'Bride Family',
      wedding_side: 'Bride',
      accompanying_members: 2,
      adults_count: 3,
      children_count: 0,
      rsvp_status: 'Confirmed',
      food_preference: 'Vegetarian',
      accommodation_required: true,
      transport_required: true,
      notes: 'Arriving from London Heathrow via Mumbai flight AI 440',
      invited_events: [eventMehendiId, eventSangeetId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-2',
      wedding_id: weddingId,
      full_name: 'Vikram Malhotra',
      phone: '+91 98111 88776',
      email: 'vikram@malhotragroup.in',
      family_group: 'VIP',
      wedding_side: 'Groom',
      accompanying_members: 1,
      adults_count: 2,
      children_count: 0,
      rsvp_status: 'Confirmed',
      food_preference: 'Non-Vegetarian',
      accommodation_required: true,
      transport_required: true,
      notes: 'Managing Director; VIP airport greeting requested',
      invited_events: [eventSangeetId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-3',
      wedding_id: weddingId,
      full_name: 'Kabir & Riya Mehta',
      phone: '+91 98450 33221',
      email: 'kabir.mehta@gmail.com',
      family_group: 'College',
      wedding_side: 'Groom',
      accompanying_members: 1,
      adults_count: 2,
      children_count: 0,
      rsvp_status: 'Confirmed',
      food_preference: 'Non-Vegetarian',
      accommodation_required: true,
      transport_required: false,
      notes: 'College roommate; leading the Sangeet dance flashmob',
      invited_events: [eventHaldiId, eventSangeetId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-4',
      wedding_id: weddingId,
      full_name: 'Ananya Sen',
      phone: '+91 97170 54321',
      email: 'ananya.sen@designstudio.com',
      family_group: 'Friends',
      wedding_side: 'Bride',
      accompanying_members: 0,
      adults_count: 1,
      children_count: 0,
      rsvp_status: 'Confirmed',
      food_preference: 'Vegan',
      accommodation_required: true,
      transport_required: true,
      notes: 'Chief bridesmaid; toast speech at reception',
      invited_events: [
        eventEngagementId,
        eventMehendiId,
        eventHaldiId,
        eventSangeetId,
        eventWeddingId,
        eventReceptionId,
      ],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-5',
      wedding_id: weddingId,
      full_name: 'Mahesh & Kanta Chawla',
      phone: '+91 94140 87654',
      email: null,
      family_group: 'Relatives',
      wedding_side: 'Bride',
      accompanying_members: 3,
      adults_count: 2,
      children_count: 2,
      rsvp_status: 'Confirmed',
      food_preference: 'Jain',
      accommodation_required: true,
      transport_required: true,
      notes: 'Strict Jain food without root vegetables',
      invited_events: [eventHaldiId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-6',
      wedding_id: weddingId,
      full_name: 'Siddharth & Priya Rao',
      phone: '+91 99000 11223',
      email: 'siddharth.rao@techcorp.io',
      family_group: 'Office',
      wedding_side: 'Groom',
      accompanying_members: 1,
      adults_count: 2,
      children_count: 0,
      rsvp_status: 'Awaiting Response',
      food_preference: 'Vegetarian',
      accommodation_required: false,
      transport_required: false,
      notes: 'Sent WhatsApp invitation reminder on Sunday',
      invited_events: [eventSangeetId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-7',
      wedding_id: weddingId,
      full_name: 'Deepak & Neha Singhania',
      phone: '+91 98300 44556',
      email: 'singhania.d@outlook.com',
      family_group: 'Friends',
      wedding_side: 'Both',
      accompanying_members: 2,
      adults_count: 2,
      children_count: 1,
      rsvp_status: 'Awaiting Response',
      food_preference: 'Vegetarian',
      accommodation_required: true,
      transport_required: true,
      notes: 'Awaiting train booking confirmation from Kolkata',
      invited_events: [eventSangeetId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-8',
      wedding_id: weddingId,
      full_name: 'Alok Verma',
      phone: '+91 98711 22334',
      email: 'alok.verma@singapore.edu.sg',
      family_group: 'Friends',
      wedding_side: 'Groom',
      accompanying_members: 0,
      adults_count: 1,
      children_count: 0,
      rsvp_status: 'Declined',
      food_preference: 'Vegetarian',
      accommodation_required: false,
      transport_required: false,
      notes: 'Overseas conference conflict; sent heartfelt wishes and gift',
      invited_events: [eventSangeetId, eventWeddingId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-gst-9',
      wedding_id: weddingId,
      full_name: 'Harish & Meena Agarwal',
      phone: '+91 98290 66778',
      email: null,
      family_group: 'Groom Family',
      wedding_side: 'Groom',
      accompanying_members: 2,
      adults_count: 3,
      children_count: 0,
      rsvp_status: 'Confirmed',
      food_preference: 'Vegetarian',
      accommodation_required: true,
      transport_required: true,
      notes: 'Groom mausa & maasi; attending all ceremonial functions',
      invited_events: [eventHaldiId, eventSangeetId, eventWeddingId, eventReceptionId],
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  ];

  const accommodations: GuestAccommodation[] = [
    {
      id: 'sample-acc-1',
      wedding_id: weddingId,
      guest_id: 'sample-gst-1',
      hotel_name: 'Rambagh Palace Heritage Wing',
      room_number: 'Room 204',
      room_type: 'Royal Garden Suite',
      check_in_date: new Date(targetDateMs - 2 * dayMs).toISOString().split('T')[0],
      check_out_date: new Date(targetDateMs + 1 * dayMs).toISOString().split('T')[0],
      occupants_count: 3,
      payment_status: 'Paid',
      status: 'Assigned',
      notes: 'Extra rollaway bed requested for daughter',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-acc-2',
      wedding_id: weddingId,
      guest_id: 'sample-gst-2',
      hotel_name: 'Rambagh Palace Heritage Wing',
      room_number: 'Suite 102',
      room_type: 'Presidential Palace Suite',
      check_in_date: new Date(targetDateMs - 1 * dayMs).toISOString().split('T')[0],
      check_out_date: new Date(targetDateMs + 1 * dayMs).toISOString().split('T')[0],
      occupants_count: 2,
      payment_status: 'Paid',
      status: 'Assigned',
      notes: 'VIP guest; fruit platter & dry fruit basket confirmed',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-acc-3',
      wedding_id: weddingId,
      guest_id: 'sample-gst-3',
      hotel_name: 'Courtyard by Marriott Jaipur',
      room_number: 'Room 412',
      room_type: 'Deluxe Twin Room',
      check_in_date: new Date(targetDateMs - 2 * dayMs).toISOString().split('T')[0],
      check_out_date: new Date(targetDateMs + 1 * dayMs).toISOString().split('T')[0],
      occupants_count: 2,
      payment_status: 'Paid',
      status: 'Assigned',
      notes: 'Near elevator',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-acc-4',
      wedding_id: weddingId,
      guest_id: 'sample-gst-4',
      hotel_name: 'Rambagh Palace Courtyard',
      room_number: 'Room 305',
      room_type: 'Heritage Superior King',
      check_in_date: new Date(targetDateMs - 3 * dayMs).toISOString().split('T')[0],
      check_out_date: new Date(targetDateMs + 1 * dayMs).toISOString().split('T')[0],
      occupants_count: 1,
      payment_status: 'Complimentary',
      status: 'Checked In',
      notes: 'Bridesmaid suite; connecting door to bridal styling room',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  ];

  const transports: GuestTransport[] = [
    {
      id: 'sample-trp-1',
      wedding_id: weddingId,
      guest_id: 'sample-gst-1',
      transport_type: 'Pickup',
      pickup_location: 'Jaipur International Airport (JAI) Terminal 2',
      destination: 'Rambagh Palace Heritage Wing',
      date: new Date(targetDateMs - 2 * dayMs).toISOString().split('T')[0],
      time: '11:30 AM',
      driver_name: 'Ramesh Singh',
      driver_phone: '+91 98290 12345',
      vehicle_details: 'Toyota Innova Crysta - RJ14 CA 7788',
      status: 'Confirmed',
      notes: 'Flight AI 440 arrival; name placard on arrival gate',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-trp-2',
      wedding_id: weddingId,
      guest_id: 'sample-gst-2',
      transport_type: 'Pickup',
      pickup_location: 'Jaipur Airport VIP Gate',
      destination: 'Rambagh Palace Heritage Wing',
      date: new Date(targetDateMs - 1 * dayMs).toISOString().split('T')[0],
      time: '03:45 PM',
      driver_name: 'Suraj Sharma',
      driver_phone: '+91 98290 55443',
      vehicle_details: 'BMW 5 Series - RJ14 TA 0001',
      status: 'Confirmed',
      notes: 'VIP charter arrival; escort to hotel lobby',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-trp-3',
      wedding_id: weddingId,
      guest_id: 'sample-gst-5',
      transport_type: 'Pickup',
      pickup_location: 'Jaipur Junction Railway Station Platform 1',
      destination: 'Hotel Fortune Bella',
      date: new Date(targetDateMs - 1 * dayMs).toISOString().split('T')[0],
      time: '07:15 AM',
      driver_name: 'Kailash Yadav',
      driver_phone: '+91 94140 99887',
      vehicle_details: 'Maruti Suzuki Ertiga - RJ14 UB 4433',
      status: 'Planned',
      notes: 'Ajmer-New Delhi Shatabdi Express',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
    {
      id: 'sample-trp-4',
      wedding_id: weddingId,
      guest_id: 'sample-gst-4',
      transport_type: 'Drop',
      pickup_location: 'Rambagh Palace',
      destination: 'Jaipur International Airport Terminal 2',
      date: new Date(targetDateMs + 1 * dayMs).toISOString().split('T')[0],
      time: '04:00 PM',
      driver_name: 'Ramesh Singh',
      driver_phone: '+91 98290 12345',
      vehicle_details: 'Toyota Innova Crysta - RJ14 CA 7788',
      status: 'Planned',
      notes: 'Flight 6E 214 departure back to Delhi',
      created_at: now.toISOString(),
      updated_at: now.toISOString(),
    },
  ];

  const vendors: Vendor[] = [
    {
      id: 'sample-vnd-1',
      wedding_id: weddingId,
      vendor_name: 'Rambagh Palace Heritage Estates',
      category: 'Venue',
      event_id: eventWeddingId,
      contact_person: 'Gajendra Singh Rathore',
      phone: '+91 98290 11223',
      whatsapp: '+919829011223',
      email: 'events@rambaghpalace.com',
      service_description: 'Bhawani Singh Road, Jaipur, Rajasthan 302005',
      status: 'Confirmed',
      agreed_amount: 200000,
      advance_amount: 150000,
      paid_amount: 150000,
      remaining_amount: 50000,
      payment_due_date: new Date(targetDateMs - 10 * dayMs).toISOString().split('T')[0],
      next_follow_up_date: null,
      notes: 'Palace Lawns & Heritage Courtyard booked for main Wedding ceremony. 50k balance due before setup.',
      created_at: new Date(now.getTime() - 20 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 14 * dayMs).toISOString(),
    },
    {
      id: 'sample-vnd-2',
      wedding_id: weddingId,
      vendor_name: 'Gourmet Feast Royal Catering',
      category: 'Catering',
      event_id: eventReceptionId,
      contact_person: 'Chef Sanjeev Mehta',
      phone: '+91 98200 44556',
      whatsapp: '+919820044556',
      email: 'catering@gourmetfeast.in',
      service_description: 'Civil Lines, Jaipur',
      status: 'Confirmed',
      agreed_amount: 200000,
      advance_amount: 95000,
      paid_amount: 95000,
      remaining_amount: 105000,
      payment_due_date: new Date(targetDateMs - 5 * dayMs).toISOString().split('T')[0],
      next_follow_up_date: null,
      notes: 'Reception royal dinner banquet with live chaat, Rajasthani thali, and dessert counters.',
      created_at: new Date(now.getTime() - 18 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
    },
    {
      id: 'sample-vnd-3',
      wedding_id: weddingId,
      vendor_name: 'Royal Floral & Mandap Decorators',
      category: 'Decoration',
      event_id: eventSangeetId,
      contact_person: 'Rajesh Saini',
      phone: '+91 98292 33445',
      whatsapp: '+919829233445',
      email: 'info@royalfloral.com',
      service_description: 'MI Road, Jaipur',
      status: 'Confirmed',
      agreed_amount: 80000,
      advance_amount: 45000,
      paid_amount: 45000,
      remaining_amount: 35000,
      payment_due_date: new Date(targetDateMs - 3 * dayMs).toISOString().split('T')[0],
      next_follow_up_date: null,
      notes: 'Sangeet stage backdrop, fairy lights canopy, and fresh marigold entrance gate.',
      created_at: new Date(now.getTime() - 15 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 4 * dayMs).toISOString(),
    },
    {
      id: 'sample-vnd-4',
      wedding_id: weddingId,
      vendor_name: 'Shutter Stories Photography',
      category: 'Photography',
      event_id: eventWeddingId,
      contact_person: 'Aman Varma',
      phone: '+91 99100 88776',
      whatsapp: '+919910088776',
      email: 'aman@shutterstories.co',
      service_description: 'Malviya Nagar, Jaipur',
      status: 'Confirmed',
      agreed_amount: 60000,
      advance_amount: 25000,
      paid_amount: 25000,
      remaining_amount: 35000,
      payment_due_date: new Date(targetDateMs + 5 * dayMs).toISOString().split('T')[0],
      next_follow_up_date: null,
      notes: 'Candid photography + cinematic teaser coverage across all 3 days.',
      created_at: new Date(now.getTime() - 12 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
    {
      id: 'sample-vnd-5',
      wedding_id: weddingId,
      vendor_name: 'Glam By Simran Kaur',
      category: 'Makeup & Beauty',
      event_id: eventMehendiId,
      contact_person: 'Simran Kaur',
      phone: '+91 97110 55432',
      whatsapp: '+919711055432',
      email: 'glambysimran@gmail.com',
      service_description: 'C-Scheme, Jaipur',
      status: 'Confirmed',
      agreed_amount: 30000,
      advance_amount: 15000,
      paid_amount: 15000,
      remaining_amount: 15000,
      payment_due_date: new Date(targetDateMs - 2 * dayMs).toISOString().split('T')[0],
      next_follow_up_date: null,
      notes: 'Bridal HD makeup + bridal organic henna styling for Mehendi ceremony.',
      created_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 1 * dayMs).toISOString(),
    },
    {
      id: 'sample-vnd-6',
      wedding_id: weddingId,
      vendor_name: 'DJ Beats & Punjabi Dhol Troupe',
      category: 'DJ / Music',
      event_id: eventSangeetId,
      contact_person: 'DJ Nikhil & Bunty',
      phone: '+91 98991 22334',
      whatsapp: '+919899122334',
      email: 'djbeatsjaipur@gmail.com',
      service_description: 'Raja Park, Jaipur',
      status: 'Confirmed',
      agreed_amount: 25000,
      advance_amount: 0,
      paid_amount: 0,
      remaining_amount: 25000,
      payment_due_date: new Date(targetDateMs - 6 * dayMs).toISOString().split('T')[0],
      next_follow_up_date: null,
      notes: 'High-energy sound setup, subwoofer rig, laser console & 2 authentic Punjabi dhol artists.',
      created_at: new Date(now.getTime() - 5 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 5 * dayMs).toISOString(),
    },
    {
      id: 'sample-vnd-7',
      wedding_id: weddingId,
      vendor_name: 'Acharya Ram Shastri',
      category: 'Priest / Rituals',
      event_id: eventWeddingId,
      contact_person: 'Pt. Ram Shastri',
      phone: '+91 94140 11998',
      whatsapp: null,
      email: null,
      service_description: 'Brahmapuri, Jaipur',
      status: 'Contacted',
      agreed_amount: 15000,
      advance_amount: 0,
      paid_amount: 0,
      remaining_amount: 15000,
      payment_due_date: null,
      next_follow_up_date: new Date(now.getTime() + 4 * dayMs).toISOString().split('T')[0],
      notes: 'Vedic rituals specialist for Vivah Muhurat. Call to finalize samagri list & timing.',
      created_at: new Date(now.getTime() - 3 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 3 * dayMs).toISOString(),
    },
  ];

  const vendorPayments: VendorPayment[] = [
    {
      id: 'sample-vpm-1',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-1',
      expense_id: 'sample-exp-1',
      amount: 150000,
      payment_date: new Date(now.getTime() - 14 * dayMs).toISOString().split('T')[0],
      paid_by: 'Dad',
      payment_method: 'Bank Transfer',
      notes: 'Initial booking deposit for Palace Lawns',
      created_at: new Date(now.getTime() - 14 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 14 * dayMs).toISOString(),
    },
    {
      id: 'sample-vpm-2',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-2',
      expense_id: 'sample-exp-2',
      amount: 95000,
      payment_date: new Date(now.getTime() - 10 * dayMs).toISOString().split('T')[0],
      paid_by: 'Mom',
      payment_method: 'Bank Transfer',
      notes: 'Menu tasting and 25% booking confirmation',
      created_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
    },
    {
      id: 'sample-vpm-3',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-3',
      expense_id: 'sample-exp-4',
      amount: 45000,
      payment_date: new Date(now.getTime() - 4 * dayMs).toISOString().split('T')[0],
      paid_by: 'Dad',
      payment_method: 'UPI',
      notes: 'Mandap floral setup advance and fairy lights',
      created_at: new Date(now.getTime() - 4 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 4 * dayMs).toISOString(),
    },
    {
      id: 'sample-vpm-4',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-4',
      expense_id: 'sample-exp-5',
      amount: 25000,
      payment_date: new Date(now.getTime() - 2 * dayMs).toISOString().split('T')[0],
      paid_by: 'Groom',
      payment_method: 'UPI',
      notes: 'Candid photographer booking for all 3 days',
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
    {
      id: 'sample-vpm-5',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-5',
      expense_id: 'sample-exp-6',
      amount: 15000,
      payment_date: new Date(now.getTime() - 1 * dayMs).toISOString().split('T')[0],
      paid_by: 'Bride',
      payment_method: 'UPI',
      notes: 'Bridal HD makeup booking token',
      created_at: new Date(now.getTime() - 1 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 1 * dayMs).toISOString(),
    },
  ];

  const vendorDocuments: VendorDocument[] = [
    {
      id: 'sample-vdoc-1',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-1',
      document_name: 'Palace Lawns Signed Agreement',
      document_type: 'Contract',
      file_reference: 'https://wedwise.internal/contracts/rambagh_palace_2026.pdf',
      uploaded_date: new Date(now.getTime() - 14 * dayMs).toISOString().split('T')[0],
      notes: 'Formal venue booking agreement signed by Gajendra Singh & Father of the Bride',
      created_at: new Date(now.getTime() - 14 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 14 * dayMs).toISOString(),
    },
    {
      id: 'sample-vdoc-2',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-2',
      document_name: 'Catering Advance Receipt (25%)',
      document_type: 'Receipt',
      file_reference: 'https://wedwise.internal/receipts/gourmet_feast_rcpt_095.pdf',
      uploaded_date: new Date(now.getTime() - 10 * dayMs).toISOString().split('T')[0],
      notes: 'GST Tax invoice with stamped token receipt',
      created_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
    },
    {
      id: 'sample-vdoc-3',
      wedding_id: weddingId,
      vendor_id: 'sample-vnd-3',
      document_name: 'Mandap Floral Architecture Blueprint',
      document_type: 'Quotation',
      file_reference: 'https://wedwise.internal/quotes/mandap_floral_design_v2.pdf',
      uploaded_date: new Date(now.getTime() - 4 * dayMs).toISOString().split('T')[0],
      notes: '3D floral layout diagram, mood board, and lighting specs',
      created_at: new Date(now.getTime() - 4 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 4 * dayMs).toISOString(),
    },
  ];

  // 12. SAMPLE FAMILY MEMBERS (WORKSPACE COLLABORATORS)
  const members: WeddingMember[] = [
    {
      id: 'sample-mem-1',
      wedding_id: weddingId,
      user_id: ownerId,
      role: 'OWNER',
      display_name: 'Priya Sharma',
      email: 'priya.wedding@example.com',
      relationship_title: 'Bride (Workspace Owner)',
      status: 'Accepted',
      joined_at: new Date(now.getTime() - 45 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 45 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 45 * dayMs).toISOString(),
    },
    {
      id: 'sample-mem-2',
      wedding_id: weddingId,
      user_id: 'usr-sunita-mom',
      role: 'FAMILY_ADMIN',
      display_name: 'Sunita Sharma',
      email: 'sunita.sharma@example.com',
      relationship_title: 'Mom',
      status: 'Accepted',
      joined_at: new Date(now.getTime() - 40 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 40 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 40 * dayMs).toISOString(),
    },
    {
      id: 'sample-mem-3',
      wedding_id: weddingId,
      user_id: 'usr-rajesh-dad',
      role: 'FAMILY_ADMIN',
      display_name: 'Rajesh Sharma',
      email: 'rajesh.sharma@example.com',
      relationship_title: 'Dad',
      status: 'Accepted',
      joined_at: new Date(now.getTime() - 38 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 38 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 38 * dayMs).toISOString(),
    },
    {
      id: 'sample-mem-4',
      wedding_id: weddingId,
      user_id: 'usr-rhea-sister',
      role: 'CONTRIBUTOR',
      display_name: 'Rhea Sharma',
      email: 'rhea.s@example.com',
      relationship_title: "Bride's Sister",
      status: 'Accepted',
      joined_at: new Date(now.getTime() - 30 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 30 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 30 * dayMs).toISOString(),
    },
    {
      id: 'sample-mem-5',
      wedding_id: weddingId,
      user_id: 'usr-vikram-uncle',
      role: 'VIEWER',
      display_name: 'Vikram Chacha Ji',
      email: 'vikram.chacha@example.com',
      relationship_title: 'Chacha Ji / Uncle',
      status: 'Accepted',
      joined_at: new Date(now.getTime() - 20 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 20 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 20 * dayMs).toISOString(),
    },
  ];

  // 13. SAMPLE INVITATIONS
  const invitations: WeddingInvitation[] = [
    {
      id: 'sample-inv-1',
      wedding_id: weddingId,
      email: 'kabir.sharma@example.com',
      role: 'CONTRIBUTOR',
      display_name: 'Kabir Sharma',
      relationship_title: "Bride's Brother",
      invited_by: ownerId,
      invited_by_name: 'Priya Sharma',
      message: 'Bhaiya, please help track hotel transfers and sangeet rehearsals on your phone!',
      status: 'Pending',
      token: 'inv-tok-kabir-brother',
      expires_at: new Date(now.getTime() + 7 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
    {
      id: 'sample-inv-2',
      wedding_id: weddingId,
      email: 'anita.bua@example.com',
      role: 'VIEWER',
      display_name: 'Anita Bua Ji',
      relationship_title: 'Bua Ji / Aunt',
      invited_by: ownerId,
      invited_by_name: 'Priya Sharma',
      message: 'Namaste Bua ji! You can view the ritual timings, venues, and room allotments here.',
      status: 'Pending',
      token: 'inv-tok-anita-bua',
      expires_at: new Date(now.getTime() + 5 * dayMs).toISOString(),
      created_at: new Date(now.getTime() - 1 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 1 * dayMs).toISOString(),
    },
  ];

  // 14. SAMPLE ACTIVITY LOG
  const activities: WeddingActivity[] = [
    {
      id: 'sample-act-1',
      wedding_id: weddingId,
      actor_user_id: 'usr-sunita-mom',
      actor_name: 'Sunita Sharma',
      actor_role: 'FAMILY_ADMIN',
      action: 'paid',
      entity_type: 'vendor_payment',
      entity_id: 'sample-vpm-2',
      entity_title: 'Gourmet Feast Royal Catering',
      metadata: {
        amount: 95000,
        details: 'Advance catering installment recorded via Bank Transfer',
      },
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
    {
      id: 'sample-act-2',
      wedding_id: weddingId,
      actor_user_id: 'usr-rajesh-dad',
      actor_name: 'Rajesh Sharma',
      actor_role: 'FAMILY_ADMIN',
      action: 'confirmed',
      entity_type: 'vendor',
      entity_id: 'sample-vnd-1',
      entity_title: 'Rambagh Palace Heritage Estates',
      metadata: {
        amount: 200000,
        details: 'Heritage palace venue booking agreement confirmed',
      },
      created_at: new Date(now.getTime() - 5 * dayMs).toISOString(),
    },
    {
      id: 'sample-act-3',
      wedding_id: weddingId,
      actor_user_id: 'usr-rhea-sister',
      actor_name: 'Rhea Sharma',
      actor_role: 'CONTRIBUTOR',
      action: 'assigned',
      entity_type: 'accommodation',
      entity_id: 'sample-acc-1',
      entity_title: 'Room 402 at The Leela Palace',
      metadata: {
        details: 'Assigned luxury room for Kapur family party',
      },
      created_at: new Date(now.getTime() - 7 * dayMs).toISOString(),
    },
    {
      id: 'sample-act-4',
      wedding_id: weddingId,
      actor_user_id: ownerId,
      actor_name: 'Priya Sharma',
      actor_role: 'OWNER',
      action: 'confirmed',
      entity_type: 'guest',
      entity_id: 'sample-gst-1',
      entity_title: 'Rajesh & Sunita Kapur',
      metadata: {
        details: 'RSVP confirmed for 4 family members',
      },
      created_at: new Date(now.getTime() - 10 * dayMs).toISOString(),
    },
    {
      id: 'sample-act-5',
      wedding_id: weddingId,
      actor_user_id: ownerId,
      actor_name: 'Priya Sharma',
      actor_role: 'OWNER',
      action: 'created',
      entity_type: 'event',
      entity_id: 'sample-evt-4',
      entity_title: 'Sangeet Night Celebration',
      metadata: {
        details: 'Created Sangeet ceremony milestone with ₹80,000 budget',
      },
      created_at: new Date(now.getTime() - 15 * dayMs).toISOString(),
    },
  ];

  const memories: WeddingMemory[] = [
    {
      id: 'sample-mem-1',
      wedding_id: weddingId,
      event_id: eventEngagementId,
      title: 'Engagement & Ring Exchange Under Starlit Canopy',
      story_caption:
        'Under the starlit floral canopy at The Leela Palace, Arjun presented the emerald-cut heirloom ring. Dadi blessed both families with ceremonial silver coins and pedas.',
      memory_date: new Date(now.getTime() - 25 * dayMs).toISOString().split('T')[0],
      milestone_phase: 'Pre-Wedding',
      location: 'The Leela Palace, Chanakyapuri, New Delhi',
      visibility: 'PUBLIC_FAMILY',
      created_by: ownerId,
      author_name: 'Priya Sharma',
      created_at: new Date(now.getTime() - 25 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 25 * dayMs).toISOString(),
    },
    {
      id: 'sample-mem-2',
      wedding_id: weddingId,
      event_id: null,
      title: 'Selecting the Banarasi Katan Bridal Saree',
      story_caption:
        'Three generations gathered in Chandni Chowk — Nani and Mum inspected the pure gold zari work, selecting a regal vermilion silk that has been handwoven for twelve weeks.',
      memory_date: new Date(now.getTime() - 18 * dayMs).toISOString().split('T')[0],
      milestone_phase: 'Pre-Wedding',
      location: 'OP Jawaharlal, Chandni Chowk, Old Delhi',
      visibility: 'CORE_FAMILY_ONLY',
      created_by: ownerId,
      author_name: 'Priya Sharma',
      created_at: new Date(now.getTime() - 18 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 18 * dayMs).toISOString(),
    },
    {
      id: 'sample-mem-3',
      wedding_id: weddingId,
      event_id: eventHaldiId,
      title: 'Haldi Sunshine & Marigold Petal Storm',
      story_caption:
        "The Leela courtyard exploded in bright yellow petals and laughter as Arjun's cousins caught him by surprise with three whole buckets of fragrant turmeric water.",
      memory_date: new Date(now.getTime() - 2 * dayMs).toISOString().split('T')[0],
      milestone_phase: 'Ceremony',
      location: 'Courtyard Gardens, The Leela Palace',
      visibility: 'PUBLIC_FAMILY',
      created_by: ownerId,
      author_name: 'Priya Sharma',
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
      updated_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
  ];

  const memoryMedia: MemoryMedia[] = [
    {
      id: 'sample-med-1',
      memory_id: 'sample-mem-1',
      wedding_id: weddingId,
      storage_path: 'sample-wedding-priya-arjun/ring-exchange-heirloom.webp',
      thumbnail_path: null,
      media_type: 'image',
      mime_type: 'image/webp',
      width: 1920,
      height: 1080,
      file_size: 420500,
      sort_order: 1,
      created_at: new Date(now.getTime() - 25 * dayMs).toISOString(),
    },
    {
      id: 'sample-med-2',
      memory_id: 'sample-mem-1',
      wedding_id: weddingId,
      storage_path: 'sample-wedding-priya-arjun/dadi-ashirwad-silver.webp',
      thumbnail_path: null,
      media_type: 'image',
      mime_type: 'image/webp',
      width: 1920,
      height: 1280,
      file_size: 512300,
      sort_order: 2,
      created_at: new Date(now.getTime() - 25 * dayMs).toISOString(),
    },
    {
      id: 'sample-med-3',
      memory_id: 'sample-mem-2',
      wedding_id: weddingId,
      storage_path: 'sample-wedding-priya-arjun/banarasi-saree-zari.webp',
      thumbnail_path: null,
      media_type: 'image',
      mime_type: 'image/webp',
      width: 1600,
      height: 1200,
      file_size: 380120,
      sort_order: 1,
      created_at: new Date(now.getTime() - 18 * dayMs).toISOString(),
    },
    {
      id: 'sample-med-4',
      memory_id: 'sample-mem-3',
      wedding_id: weddingId,
      storage_path: 'sample-wedding-priya-arjun/haldi-marigold-splash.webp',
      thumbnail_path: null,
      media_type: 'image',
      mime_type: 'image/webp',
      width: 2048,
      height: 1365,
      file_size: 685400,
      sort_order: 1,
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
    {
      id: 'sample-med-5',
      memory_id: 'sample-mem-3',
      wedding_id: weddingId,
      storage_path: 'sample-wedding-priya-arjun/haldi-family-portrait.webp',
      thumbnail_path: null,
      media_type: 'image',
      mime_type: 'image/webp',
      width: 1920,
      height: 1080,
      file_size: 490200,
      sort_order: 2,
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
  ];

  const memoryPeopleTags: MemoryPeopleTag[] = [
    {
      id: 'sample-mtag-1',
      memory_id: 'sample-mem-1',
      wedding_id: weddingId,
      guest_id: 'sample-gst-1',
      custom_name: 'Rajesh & Sunita Kapur',
      relationship_tag: 'Maternal Uncle & Aunt',
      created_at: new Date(now.getTime() - 25 * dayMs).toISOString(),
    },
    {
      id: 'sample-mtag-2',
      memory_id: 'sample-mem-1',
      wedding_id: weddingId,
      guest_id: null,
      custom_name: 'Dadi (Kailash Sharma)',
      relationship_tag: 'Grandmother',
      created_at: new Date(now.getTime() - 25 * dayMs).toISOString(),
    },
    {
      id: 'sample-mtag-3',
      memory_id: 'sample-mem-2',
      wedding_id: weddingId,
      guest_id: null,
      custom_name: 'Meenakshi Sharma',
      relationship_tag: 'Mother of Bride',
      created_at: new Date(now.getTime() - 18 * dayMs).toISOString(),
    },
    {
      id: 'sample-mtag-4',
      memory_id: 'sample-mem-3',
      wedding_id: weddingId,
      guest_id: 'sample-gst-3',
      custom_name: 'Amit & Neha Verma',
      relationship_tag: 'Close Friends',
      created_at: new Date(now.getTime() - 2 * dayMs).toISOString(),
    },
  ];

  return {
    wedding,
    categories,
    expenses,
    events,
    tasks,
    guests,
    accommodations,
    transports,
    vendors,
    vendorPayments,
    vendorDocuments,
    members,
    invitations,
    activities,
    memories,
    memoryMedia,
    memoryPeopleTags,
  };
}
